apiVersion: v1
kind: Config
clusters:
- name: your-cluster
  cluster:
    server: https://192.168.49.2:8443(vehicle)
    certificate-authority-data: <BASE64_CA_CERT>
users:
- name: jenkins-user
  user:
    token: <YOUR_SERVICE_ACCOUNT_OR_USER_TOKEN>
contexts:
- name: jenkins-context
  context:
    cluster: your-cluster
    user: jenkins-user
    namespace: mlops
current-context: jenkins-context
