apiVersion: v1
kind: Secret
metadata:
  name: vehicle-insurance-secret

type: Opaque

stringData:
  MONGODB_URL: "mongodb+srv://vikassharadha2006:Vikas%402006@cluster0.exie5sc.mongodb.net/?appName=Cluster0"
