apiVersion: v1
kind: Service
metadata:
  name: vehicle-insurance-service

spec:
  selector:
    app: vehicle-insurance

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer
